### ISSUE TITLE
Account activity stream not working

### ISSUE THREAD

**Issue by tagavii** [alexgolec/schwab-py#117] opened 2024-06-02 16:08 UTC
**Description of Bug**
This might be on you radar, but account activity stream [ACCT_ACTIVITY] isn't working anymore (used to with tda API as shown below). The issue is probably due to modifications by Schwab, where “SchwabClientCustomerId” and “SchwabClientCorrelId” are now used. This is different from TDA, where the “account_id” was included directly during subscription.

**Code to Reproduce**
The schwab-py streaming example modified to only subscribe to account updates. Changes shown below.

    def initialize(self):
        self.stream_client = StreamClient(self.tda_client, account_id=self.account_id)

        self.stream_client.add_account_activity_handler(self.queue_manager)
            

    async def stream(self):
        await self.stream_client.login()  # Log into the streaming service
        
        await self.stream_client.account_activity_sub()
        
        (etc.)

    async def data_pipeline(self):
        while True:
            data = await self.queue.get()
            #
            if data!=None:
                write_to_json_file(data['content'])

**Expected Behavior**
Subscription confirmation, plus continuous stream of account activities. Note the "ACCOUNT" value using TD-Ameritrade.

![image](https://github.com/alexgolec/schwab-py/assets/63385373/68a4d884-e8af-4765-97e3-3374d162f868)
  

**Actual Behavior**
Subscription confirmation. No further account activity is registered or streamed.
![image](https://github.com/alexgolec/schwab-py/assets/63385373/6c23c36d-e8b1-4a3d-9a8e-e41be7ae7045)

**Comment by alexgolec** [comment] 2024-06-03 19:51
`The issue is probably due to modifications by Schwab, where “SchwabClientCustomerId” and “SchwabClientCorrelId” are now used. This is different from TDA, where the “account_id” was included directly during subscription.` Can you please elaborate on this? I'm not sure I follow. 

Also, it looks to me from your actual behavior that the stream connects and receives data, just not the sort of data you received previously from TDA ?

**Comment by tagavii** [comment] 2024-06-06 00:43
You're right, the stream connects and gets the initial confirmation message but then nothing else. Account activities should be passed via WebSocket, like TDA used to do. Thanks for checking it out.

The “SchwabClientCustomerId” and “SchwabClientCorrelId” bit was just a guess. During login part of streaming,  "get_user_preferences" returns accounts and streamerInfo, shown below. But only streamerInfo is used. In TDA, we'd specify the account with account_id. Just something to consider.

<img width="188" alt="Screenshot 2024-06-05 194038" src="https://github.com/alexgolec/schwab-py/assets/63385373/493f2181-d089-4d39-8d40-40a75f25452e">

**Comment by kelaraj** [comment] 2024-06-12 20:17
FYI it looks like the issue is with Schwab. Schwab support today:
"We are still currently working out some issues with the ACCT_ACTIVITY streamer, so it will not work correctly at this time. We are hoping to have it working in the very near future, but we unfortunately do not have an exact eta for when it will be fully up and running."

I am also able to subscribe to ACCT_ACTIVITY via `account_activity_sub` and receive a subscription confirmation message, but no actual activity updates are sent.

**Comment by alexgolec** [comment] 2024-06-13 04:04
Closing this because this appears to be an issue on Schwab's side.

**Closed by alexgolec** 2024-06-13 04:04 UTC
Labels: bug, streaming

**Comment by mecampbellsoup** [comment] 2026-05-21 15:29
**Update (May 2026): Account activity streaming is now working.**

We verified this today using `schwab-py` with Python 3.14. The `ACCT_ACTIVITY` service delivers real-time order lifecycle events via the websocket stream.

**What works:**
- `account_activity_sub()` subscribes successfully
- Real-time events for the full order lifecycle: `OrderCreated`, `OrderAccepted`, `ExecutionRequested`, `ExecutionRequestCreated`, `ExecutionRequestCompleted`
- Cancel events: `CancelAccepted`, `ExecutionCreated`, `OrderUROutCompleted`
- `MESSAGE_DATA` contains a JSON string (double-parse needed) with full order details — order ID, account number, legs, quotes at time of order, routing info

**Gotcha that may cause false negatives:**
Schwab only allows **one streaming connection per user**. If you have another stream open (e.g., a quote streamer, or orphan processes from a previous run), the new connection gets kicked immediately with:

> "This Streamer was disconnected because of another connection for this username and password. Each user may only have one connection open at a time."

This manifests as the stream connecting, sending one or two `SUBSCRIBED` heartbeats, then closing with websocket code 1000 (OK). If you're only seeing `SUBSCRIBED` messages and no order events, check for orphan stream processes.

**Minimal reproduction:**
```python
stream = StreamClient(client)
stream.add_account_activity_handler(lambda msg: print(json.dumps(msg, indent=2)))
await stream.login()
await stream.account_activity_sub()
while True:
    await stream.handle_message()
```
