### ISSUE TITLE
unable to extract order id using the utils

### ISSUE THREAD

**Issue by jhayre** [alexgolec/schwab-py#17] opened 2024-04-22 21:23 UTC
## Please read the [bug submission guidelines](https://tda-api.readthedocs.io/en/latest/help.html) before submitting a bug.

Not following guidelines may result in your bug being ignored and/or closed. 

**Description of Bug**
<DESCRIPTION>

**Code to Reproduce**
Paste in the code that causes the bug to occur. 

IMPORTANT: Remember to anonymize your code. Be sure to replace API keys/Client IDs with placeholders. Also, never, ever share the contents of your token file. 

**Expected Behavior**
<EXPECTED BEHAVIOR>

**Actual Behavior**
<ACTUAL BEHAVIOR>

**Error/Exception Log, If Applicable**
See here to learn how to turn on debug logging: https://tda-api.readthedocs.io/en/latest/help.html

**Comment by alexgolec** [comment] 2024-04-25 12:48
Closing due to lack of information. Please follow issue templates to help me reproduce your issue. Feel free to edit your description and reopen the issue.

**Closed by alexgolec** 2024-04-25 12:48 UTC
