### ISSUE TITLE
Login error when using client_from_login_flow

### ISSUE THREAD

**Issue by felonfusk** [alexgolec/schwab-py#149] opened 2024-07-04 13:28 UTC
## Please read the [bug submission guidelines](https://tda-api.readthedocs.io/en/latest/help.html) before submitting a bug.

Not following guidelines may result in your bug being ignored and/or closed. 

**Description of Bug**
Trying to use `client_from_login_flow ` to get a new token. But received error at Schwab login.
![error](https://github.com/alexgolec/schwab-py/assets/124466530/84c60cc6-2069-41ef-981d-3fa1bd03513e)

My credential is correct, as I was able to login and create new tokens without using `client_from_login_flow `
The same error happens to `client_from_manual_flow` as well.

python: 3.11
schwab-py: 1.2.1

**Code to Reproduce**
```
import schwab
api_key = ""
app_secret = ""
callback_url = "https://127.0.0.1:8182"
token_path = 'token.json'

def login_works():
    import webbrowser
    auth_url = (f"https://api.schwabapi.com/v1/oauth/authorize"
                   f"?client_id={api_key}&redirect_uri=https://127.0.0.1")
    webbrowser.open(auth_url)

def login_error():
    schwab.auth.client_from_login_flow(api_key, app_secret, callback_url, token_path)

```

**Expected Behavior**
Log into Schwab's account page

**Actual Behavior**
Error at Schwab login screen

**Error/Exception Log, If Applicable**
See here to learn how to turn on debug logging: https://tda-api.readthedocs.io/en/latest/help.html

**Comment by alexgolec** [comment] 2024-07-05 20:00
I can't help but notice that you're sending two different callback URLs there. The one in `login_works` sends `https://127.0.0.1` whereas the one in login_error sends `https://127.0.0.1:8182`. Are you sure you're not setting the wrong callback URL? I've encountered this same error in the past and was similarly confused.

**Comment by alexgolec** [comment] 2024-07-05 20:38
Are both `https://127.0.0.1:8182` and `https://127.0.0.1` configured as callback URLs for your application? The situation you describe is exactly what happens if you attempt to pass anything that isn't a configured callback.

**Comment by felonfusk** [comment] 2024-07-05 20:49
You are right. My app settings show the callback url is just `https://127.0.0.1`, without the port number.
I just created a 2nd app with `https://127.0.0.1:8182` this time, will report back once it's approved.

**Comment by alexgolec** [comment] 2024-07-05 22:02
Working as intended, marking as won't fix. 

As an FYI, I haven't had any success getting a second app approved, you may find it goes into the `Approved - Pending` state forever. I recommend updating your existing app to either modify the existing callback URL to include a port number, or adding a new callback URL alongside the existing one. If the only thing that's using your callback URL is `schwab-py`, I recommend the first option.

**Closed by alexgolec** 2024-07-05 22:02 UTC
Labels: bug, authentication
